{% set name = "egl-probe" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/egl_probe-{{ version }}.tar.gz
  sha256: 29bdca7b08da1e060cfb42cd46af8300a7ac4f3b1b2eeb16e545ea16d9a5ac93
  patches:
    # Do not include the sources and the build directory in the wheel, see
    # https://github.com/StanfordVL/egl_probe/pull/4
    - 4.patch

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - egl_probe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/StanfordVL/egl_probe
  license: MIT
  license_file: LICENSE
  summary: A helpful module for listing available GPUs for EGL rendering. 

extra:
  recipe-maintainers:
    - traversaro
